import type { Metadata } from "next";
import { Schibsted_Grotesk, } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'

const ltInstitute = localFont({src: './fonts/LTInstitute-1.otf'})

const fustat = localFont({src: './fonts/Fustat[wght].ttf'})

const grotesk = Schibsted_Grotesk({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ltInstitute.className}>
        {children}
      </body>
    </html>
  );
}
